ver:1
Oligarhselmasha/java-filmorate pull request #4
Opened 2023-02-17 18:04 UTC by Oligarhselmasha

2023-02-18 12:52 UTC, AnastasiyaFomkina requested changes
Добавь, пожалуйста, схему базы данных в readme.md

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    public Collection<Mpa> showMpa() {
`Collection` слишком абстрактный интерфейс, лучше сузить до более логичного - `List`

 Поправь, пожалуйста, во всем проекте

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                    .get();
Прежде чем получать значение из `Optional` нужно убедиться, что он не пустой. Можно воспользоваться любым способом из [данной статьи](https://habr.com/ru/post/346782/#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%2C%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%89%D0%B8%D0%B9%D1%81%D1%8F%20%D0%B2%20Optional%3F)

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                .get();
И здесь тоже, нужно сначала убедиться, что `Optional` не пуст

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            if (film.getGenres() != null) {
Здесь тоже

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (film.getGenres() != null) {
Это выражение всегда будет возвращать `true`, так как мы всегда инициализирую список `genres` массивом. Нужно удалить проверку

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            film.getGenres().forEach(g -> jdbcTemplate.update(sqlGenreAdd, keyHolder.getKey().intValue(), g.toString()));
Прежде чем получать `intValue`, нужно проверить, что `keyHolder.getKey() != null`. 
Потом можно будет записать результат работы в отдельную переменную, чтобы переиспользовать в строке 68

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        return getFilmById(keyHolder.getKey().intValue());
Не хватает проверки на `null`

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            if (film.getGenres().size() == 0) {
Лучше использовать метод [isEmpty()](https://www.geeksforgeeks.org/java-string-isempty-method-example/)
```suggestion
            if (film.getGenres().isEmpty()) {
```
он более читаемый

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                String sqlDeleteGenres = "delete from Genres_line where FILM_ID = ?";
Повторяющиеся запросы можно вынести в константы

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenresDAOImpl.java
> +            return jdbcTemplate.query(sql, (rs, rowNum) -> makeGenres(rs), id).stream().findFirst().get();
Стримы лучше бить по строкам, чтобы улучшить читаемость кода:
```suggestion
            return jdbcTemplate.query(
                    sql, (rs, rowNum) -> makeGenres(rs), id
                ).stream()
                .findFirst()
                .get();
```
Прежде чем получать значение из `Optional`, нужно проверить, что он не пуст

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenresDAOImpl.java
> +       return Genres.builder().id(rs.getInt("GENRE_ID")).name(rs.getString("GENRE")).build();
Билдеры тоже лучше бить по строкам:
```suggestion
       return Genres.builder()
            .id(rs.getInt("GENRE_ID"))
            .name(rs.getString("GENRE"))
            .build();
```

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/MpaDAOImpl.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> makeMPA(rs), id).stream().findFirst().get();
Нужно побить стрим по строкам и проверить, что `Optional` не пуст

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/MpaDAOImpl.java
> +            return jdbcTemplate.query(sql, (rs, rowNum) -> makeMPA(rs), id).stream().findFirst().get();
Нужно побить стрим по строкам и проверить, что `Optional` не пуст

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/MpaDAOImpl.java
> +        return Mpa.builder().id(rs.getInt("RATING_ID")).name(rs.getString("RATING_NAME")).build();
Нужно побить по строкам

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        return getUserById(keyHolder.getKey().intValue());
Не хватает проверки на `null`

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        jdbcTemplate.update(new PreparedStatementCreator() {
Нужно заменить на лямбду

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        jdbcTemplate.update(new PreparedStatementCreator() {
[Функциональные интерфейсы](https://www.baeldung.com/java-8-functional-interfaces) после java 8 очень удобно обрабатывать с помощью lambda-выражений. Предлагаю попробовать переписать

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +                    .get();
Получение `Optional` без проверки

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        for (User user : getUsers()) {
Нужно переписать через `forEach()` или `stream api`

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            throw new MissingException("Пользователь, которого Вы пытаетесь обновить, отсутствует в базе.");
Можно вынести сообщение об ошибке в константу и переиспользовать

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTest.java
> +//!!!Тесты запускать все разом. Порядок запуска тестов имеет значение!!!
Чтобы тесты не зависели друг от друга, нужно разбить их на разные классы. В тз требуется добавить тестирование для методов стораджа. Каждый из стороджей нужно тестировать отдельно в своем классе, чтобы данные не перетирались. Если тестовое окружение для тестирования, нужные компоненты в базу перед запуском каждого из тестов с помощью конфигурационного метода с аннотацией [@BeforeEach](https://habr.com/ru/post/590741/). 
Вот пример теста из тз, можно опираться на него:
```
@SpringBootTest
@AutoConfigureTestDatabase
@RequiredArgsConstructor(onConstructor_ = @Autowired)
class FilmoRateApplicationTests {
    private final UserDbStorage userStorage;

    @Test
    public void testFindUserById() {

        Optional<User> userOptional = userStorage.findUserById(1);

        assertThat(userOptional)
                .isPresent()
                .hasValueSatisfying(user ->
                        assertThat(user).hasFieldOrPropertyWithValue("id", 1)
                );
    }
} 
```
Старые тесты на валидацию удалять не нужно.

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +        Film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Лучше поправить название колонок по [sql-style](https://www.sqlstyle.guide/)

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +		Genre_id integer-- NOT NULL
Лучше не оставлять закомментированные куски скрипта

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +        CONSTRAINT bad_email  CHECK (Email LIKE '%___@___%.__%')
Клево, что добавил валидацию - молодец 👍

2023-02-18 12:52 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +drop table  IF EXISTS Genres CASCADE;
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-02-20 06:11 UTC, Oligarhselmasha commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (film.getGenres() != null) {
Позвольте не согласится. Когда я получаю json по типу,
```
{
  "name": "nisi eiusmod",
  "description": "adipisicing",
  "releaseDate": "1967-03-25",
  "duration": 100,
  "mpa": { "id": 1}
}
```
мне в приложение прилетает как раз фильм с genres равным null. Один из вариантов, сделать финальную переменную инициализированную   в классе Film  `private final List<Genres> genres = new ArrayList<>();` , но тогда я не могу через @Builder собирать фильм. Предлагаю все таки оставить.

2023-02-20 06:13 UTC, Oligarhselmasha commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (film.getGenres() != null) {
Мне самому не нравится нагромождение ифов, но без этого похоже никак, я пробовал не проверять, в указанном выше примере прилетает именно null

2023-02-20 07:27 UTC, Oligarhselmasha commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            film.getGenres().forEach(g -> jdbcTemplate.update(sqlGenreAdd, keyHolder.getKey().intValue(), g.toString()));
`Objects.requireNonNull(keyHolder.getKey())`
Идея предложила проверить таким способом

2023-02-20 17:10 UTC, Oligarhselmasha commented
> Добавь, пожалуйста, схему базы данных в readme.md

через Идею почему- то не видно, а так тут все есть

2023-02-21 16:52 UTC, AnastasiyaFomkina requested changes

2023-02-21 16:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (film.isPresent()) {
Можно написать в функциональном стиле и сильно сократить код, если использовать метод для получения значения из `Optional`.
`.orElseThrow()` - разварачивает `Optional`, если в нем есть значение. Если он пуст - то выбрасывает исключение:
``` suggestion
return jdbcTemplate.query(
                sql, (rs, rowNum) -> makeGenres(rs), id
            ).stream()
            .findFirst()
            .orElseThrow(() -> new MissingException(BAD_GENRE.getException()));
```

2023-02-21 16:52 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Давай декомпозируем большой класс на несколько подклассов для каждой сущности. Тогда у нас получится 4 класса с тестами для mpa, genres, user и film

2023-02-21 16:52 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +        Name varchar(40) NOT NULL,
Лучше поправить название колонок по [sql-style](https://www.sqlstyle.guide/)

2023-02-21 16:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genres> genres = new ArrayList<>();
Инициализация лишняя, мы инициализируем это поле через конструктор, который генерирует lombok

```suggestion
    private List<Genres> genres;
```

2023-02-21 16:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            if (film.getGenres() != null) {
Ошиблась на прошлой итерации, здесь можно просто убрать проверку:
нужно удалить строки 86, 98 и 99.

2023-02-24 08:16 UTC, AnastasiyaFomkina approved these changes

2023-02-24 10:48 UTC, merged